sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: FtNAOgigA5dBgv7PYQeZWdICTr4T0ocBBUflb2c92NhyDf/qKdEEm7Vfgz2HgidcM+G/iJXwneDSKBcKPOAX5kXZ+OCYIsXp3smHPGnpyNugo1zJGkltyXC4BIf0oD/U5X7USJ5Srgq1K2j/BOlnHzH+0Mmucz/APA+dQo0GwTshrsWFFd8uF2fcwUVBdzeGUP0hKksoGPocUXN3TLRg7jzv/BFpF2mN0uI+4ajL+mCwTFeoq1Vww04WnPQ3bRT8uPBy1Z/tOMnOnnfO/m12MZa7LaSYIysxQw9hsONOdc3rCLBGBXRBDbfbHS+LBW5U501/2q5wi5/zDmT0V2NuNsnCgSJSGc1lGPHqd3MQoNefnF5KlZxNZ8UjSmTAGr8/mU31SHgtEjupJDTYaTkxvgoR86pXckjCJuWCaioXrwRx+X7FV3YRnfAppjtqI8NEiNo+F8DQm7rwyWeFuW31mQcxmIz+Y7GoFHt8JQrMCoqkWHpSYTbR+VN7xQ8i42j8Slr0h5s/Es2GntGeWWkqJRNV+l8KltlFreRcb+QWWsibaEmZ1AiK3ipq0C7t1GPo0Lm8FK+rOwLwZiwCabixOpNGN9VIxcgbrgLw91nmvkciewg6og72iCxBhkThg75tQ6+jgVu7FxrOxp8WoZCKuMSV3K/OJxfaVJeoKwMNMB0=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/The-Sorrows-of-Young-Werther_2527
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy